SELECT [ProductKey]
      ,[OrderDateKey]
      --,[DueDateKey]
      --,[ShipDateKey]
      --,[CustomerKey]
      --,[PromotionKey]
      --,[CurrencyKey]
      ,[SalesTerritoryKey]
      ,[SalesOrderNumber] AS OrderNumber
      --,[SalesOrderLineNumber]
      --,[RevisionNumber]
      --[OrderQuantity]
      --[UnitPrice]
      --[ExtendedAmount]
      --[UnitPriceDiscountPct]
      --[DiscountAmount]
      --[ProductStandardCost]
      ,[TotalProductCost]
      ,[SalesAmount]
      --,[TaxAmt]
      --,[Freight]
      --,[CarrierTrackingNumber]
      --,[CustomerPONumber]
      ,[OrderDate]
      --,[DueDate]
      --,[ShipDate]
	  ,[SalesAmount] - [TotalProductCost] AS ProductProfit
  FROM [AdventureWorksDW2022].[dbo].[FactInternetSales]
  WHERE LEFT([OrderDateKey],4) BETWEEN 2021 AND 2022  --Returns only years 2021 & 2022